stages:
  - build
  - test
  - deploy

update tests image:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/tests --dockerfile $CI_PROJECT_DIR/tests/Dockerfile --destination $CI_REGISTRY_IMAGE/tests
  only:
    - branches

run unit tests:
  stage: test
  image: $CI_REGISTRY_IMAGE/tests
  script: tox
  only:
    - branches

check guidelines:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  script: codestyle ./ --quiet --exclude './tests/data'
  only:
    - branches

update latest image:
  stage: deploy
  image: gcr.io/kaniko-project/executor:debug
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
  only:
    - master
